-- Production schema reference for QR Display App.
-- The live Supabase project has already been initialized.
-- If recreating the project elsewhere, replace <ADMIN_SETUP_SHA256>
-- with SHA-256 of a strong one-time admin setup code before running.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.qr_config (
  id bigint primary key,
  url text not null,
  title text not null default 'Quét mã QR để truy cập',
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id) on delete set null
);

create table if not exists public.qr_history (
  id bigint generated by default as identity primary key,
  url text not null,
  title text,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

create table if not exists public.app_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

insert into public.qr_config (id, url, title)
values (1, 'https://example.com', 'Quét mã QR để truy cập')
on conflict (id) do nothing;

-- For a fresh install only, uncomment after replacing the placeholder:
-- insert into public.app_settings (key, value)
-- values ('admin_setup_hash', '<ADMIN_SETUP_SHA256>')
-- on conflict (key) do update set value = excluded.value, updated_at = now();

alter table public.qr_config enable row level security;
alter table public.qr_history enable row level security;
alter table public.app_admins enable row level security;
alter table public.app_settings enable row level security;

revoke all on table public.qr_config from anon, authenticated;
revoke all on table public.qr_history from anon, authenticated;
revoke all on table public.app_admins from anon, authenticated;
revoke all on table public.app_settings from anon, authenticated;

grant select on table public.qr_config to anon, authenticated;
grant select on table public.qr_history to authenticated;

drop policy if exists "Public can read current QR" on public.qr_config;
create policy "Public can read current QR"
on public.qr_config
for select
to anon, authenticated
using (true);

create or replace function public.is_current_user_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select auth.uid() is not null
    and exists (
      select 1 from public.app_admins where user_id = auth.uid()
    );
$$;

revoke all on function public.is_current_user_admin() from public, anon, authenticated;
grant execute on function public.is_current_user_admin() to authenticated;

drop policy if exists "Admin can read history" on public.qr_history;
create policy "Admin can read history"
on public.qr_history
for select
to authenticated
using ((select public.is_current_user_admin()));

create or replace function public.claim_admin(setup_code text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  stored_hash text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required';
  end if;

  if exists (select 1 from public.app_admins where user_id = auth.uid()) then
    return true;
  end if;

  if exists (select 1 from public.app_admins) then
    return false;
  end if;

  select value into stored_hash
  from public.app_settings
  where key = 'admin_setup_hash'
  for update;

  if stored_hash is null then
    return false;
  end if;

  if encode(extensions.digest(setup_code, 'sha256'), 'hex') <> stored_hash then
    return false;
  end if;

  insert into public.app_admins (user_id) values (auth.uid());
  delete from public.app_settings where key = 'admin_setup_hash';
  return true;
end;
$$;

revoke all on function public.claim_admin(text) from public, anon, authenticated;
grant execute on function public.claim_admin(text) to authenticated;

create or replace function public.update_qr(p_url text, p_title text)
returns public.qr_config
language plpgsql
security definer
set search_path = ''
as $$
declare
  result public.qr_config;
  normalized_title text;
begin
  if auth.uid() is null or not exists (
    select 1 from public.app_admins where user_id = auth.uid()
  ) then
    raise exception 'Admin permission required';
  end if;

  if p_url is null or p_url !~* '^https?://[^[:space:]]+$' then
    raise exception 'Only http:// or https:// URLs are allowed';
  end if;

  normalized_title := coalesce(nullif(btrim(p_title), ''), 'Quét mã QR để truy cập');
  if char_length(normalized_title) > 80 then
    raise exception 'Title is too long';
  end if;

  insert into public.qr_history (url, title, created_by)
  values (p_url, normalized_title, auth.uid());

  update public.qr_config
  set url = p_url,
      title = normalized_title,
      updated_at = now(),
      updated_by = auth.uid()
  where id = 1
  returning * into result;

  return result;
end;
$$;

revoke all on function public.update_qr(text, text) from public, anon, authenticated;
grant execute on function public.update_qr(text, text) to authenticated;

alter table public.qr_config replica identity full;

-- Run only once on a fresh project if qr_config is not already in Realtime:
-- alter publication supabase_realtime add table public.qr_config;
