-- Chạy toàn bộ file này trong Supabase SQL Editor.

create table if not exists public.qr_config (
  id bigint primary key,
  url text not null,
  title text not null default 'Quét mã QR để truy cập',
  updated_at timestamptz not null default now()
);

create table if not exists public.qr_history (
  id bigint generated by default as identity primary key,
  url text not null,
  title text,
  created_at timestamptz not null default now()
);

insert into public.qr_config (id, url, title)
values (1, 'https://example.com', 'Quét mã QR để truy cập')
on conflict (id) do nothing;

alter table public.qr_config enable row level security;
alter table public.qr_history enable row level security;

-- Public được xem QR hiện tại.
create policy "Public can read current QR"
on public.qr_config for select
using (true);

-- Chỉ người đã đăng nhập mới được cập nhật QR.
create policy "Authenticated can update current QR"
on public.qr_config for update
to authenticated
using (true)
with check (true);

-- Admin đã đăng nhập có thể xem + thêm lịch sử.
create policy "Authenticated can read history"
on public.qr_history for select
to authenticated
using (true);

create policy "Authenticated can insert history"
on public.qr_history for insert
to authenticated
with check (true);

-- Bật realtime cho bảng qr_config.
alter publication supabase_realtime add table public.qr_config;
